//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET_USER_RELATIONSHIP
    {
        public int ASSET_USER_RELATIONSHIP_ID { get; set; }
        public int AS_ID { get; set; }
        public int U_ID { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<System.DateTime> HAND_OVER_DATE { get; set; }
    
        public virtual ASSET ASSET { get; set; }
        public virtual USER USER { get; set; }
    }
}
