//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET_REQUEST
    {
        public int AR_ID { get; set; }
        public int U_ID { get; set; }
        public int RT_ID { get; set; }
        public int AS_ID { get; set; }
        public string AR_REASON { get; set; }
        public string AR_ASSET_STATUS { get; set; }
        public Nullable<System.DateTime> AR_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> AR_APPROVE_DATE { get; set; }
        public string AR_STATUS { get; set; }
    
        public virtual ASSET ASSET { get; set; }
        public virtual REQUEST_TYPE REQUEST_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
