//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSET()
        {
            this.ASSET_REQUEST = new HashSet<ASSET_REQUEST>();
            this.ASSET_USER_RELATIONSHIP = new HashSet<ASSET_USER_RELATIONSHIP>();
            this.HAND_OVER = new HashSet<HAND_OVER>();
        }
    
        public int AS_ID { get; set; }
        public int AT_ID { get; set; }
        public string AS_NAME { get; set; }
        public string AS_STATUS { get; set; }
        public Nullable<System.DateTime> AS_PURCHASE_DATE { get; set; }
        public string AS_PROVIDER { get; set; }
        public string AS_DESCRIPTION { get; set; }
        public Nullable<int> AS_VALUE { get; set; }
        public Nullable<bool> AS_FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET_REQUEST> ASSET_REQUEST { get; set; }
        public virtual ASSET_TYPE ASSET_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET_USER_RELATIONSHIP> ASSET_USER_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAND_OVER> HAND_OVER { get; set; }
    }
}
