//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAND_OVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAND_OVER()
        {
            this.ASSETs = new HashSet<ASSET>();
        }
    
        public int HO_ID { get; set; }
        public int U_SEND_ASSET { get; set; }
        public int U_RECEIVE_ASSET { get; set; }
        public Nullable<System.DateTime> HO_DATE { get; set; }
        public string HO_CONntext { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET> ASSETs { get; set; }
    }
}
