//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ASSET_REQUEST = new HashSet<ASSET_REQUEST>();
            this.ASSET_USER_RELATIONSHIP = new HashSet<ASSET_USER_RELATIONSHIP>();
            this.HAND_OVER = new HashSet<HAND_OVER>();
            this.HAND_OVER1 = new HashSet<HAND_OVER>();
        }
    
        public int U_ID { get; set; }
        public int UT_ID { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_FULLNAME { get; set; }
        public Nullable<System.DateTime> U_WORK_DATE { get; set; }
        public string U_STATUS { get; set; }
        public string U_POSITION { get; set; }
        public string U_DEPARTMENT { get; set; }
        public Nullable<bool> U_FLAG { get; set; }
        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET_REQUEST> ASSET_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSET_USER_RELATIONSHIP> ASSET_USER_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAND_OVER> HAND_OVER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAND_OVER> HAND_OVER1 { get; set; }
        public virtual USER_TYPE USER_TYPE { get; set; }
    }
}
